### ISSUE TITLE
FOUC with home page number

### ISSUE THREAD

**Issue by lilith** [lilith/playdate#21]
It's not essential that the phone number box be stylistically matched, but at the moment the home page displays all country prefixes for a moment before it sorts itself out.

**Comment by jho44** [comment]
Pretty sure this was resolved at some point but lmk if it still shows FOUC for you!

**Comment by lilith** [comment]
Actually, I was able to reproduce this. Ctrl+Shift+R from desktop browser clears the cache, which is the default state for new visitors.

**Comment by jho44** [comment]
https://github.com/lilith/playdate/assets/45194378/9f6578c6-135f-4416-9023-6dcfb7413116

This is what I see after a cmd-shift-R. Lmk if you can still reproduce it x.x
