### ISSUE TITLE
Text schedule when a friend request is accepted

### ISSUE THREAD

**Issue by lilith** [lilith/playdate#54]
If you create an account and accept a friend request, their schedule should be automatically texted to you, and they should be notified by text that they're in your circle now.

**Comment by lilith** [comment]
This should go out after the FAQ link

**Comment by jho44** [comment]
the sched should be sent to all members in the household right? and the subsequent notif about being in each other's circle should be sent to all members in the other household right?

**Comment by lilith** [comment]
Yes, that's right. Both households should receive each others schedules
when the friend request is accepted.

And when you update your own schedule, your own household can be notified
too
